"""VUSA AI DAILY INTELLIGENCE REPORT (Markdown + standalone HTML).

Every number in the report is read from the structured state - nothing is typed in by
hand or generated by a language model."""
from __future__ import annotations

import html as _html

import numpy as np


def _p(x, d=1, sign=True):
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "n/a"
    return f"{100 * x:{'+' if sign else ''}.{d}f}%"


def _n(x, d=1):
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "n/a"
    return f"{x:.{d}f}"


def build_report(st: dict) -> tuple[str, str]:
    d, fc, rg = st.get("decision", {}), st.get("forecast_primary", {}), st.get("regime", {})
    cur = st.get("currency", "EUR")
    sym = "€" if cur == "EUR" else ("£" if cur == "GBP" else "")
    L = []
    L.append("# VUSA AI DAILY INTELLIGENCE REPORT")
    if st.get("is_synthetic"):
        L.append("\n> **SYNTHETIC DEMO DATA - NOT REAL MARKET DATA. Nothing in this report describes the real market.**")
    elif not st.get("data_current"):
        L.append("\n> **🟡 DATA NOT CURRENT** - the assessment is based on the latest available (cached/delayed) data.")
    L.append(f"\n**Date (last session):** {st.get('as_of')}  |  **Run:** {st.get('run_id')}  |  **Mode:** {st.get('mode')}")
    L.append(f"\n**Current price:** {sym}{_n(st.get('price'), 2)} ({st.get('symbol')})  |  **Data:** {st.get('data_status')}")
    L.append("\n## Decision")
    L.append(f"| Signal | Opportunity | Risk | Confidence | Model agreement | Final score |\n|---|---|---|---|---|---|\n"
             f"| **{d.get('label')}** | {_n(d.get('opportunity'), 0)}/100 | {_n(d.get('risk'), 0)}/100 | "
             f"{_p(d.get('confidence'), 0, False)} | {_p((fc.get('disagreement') or {}).get('sign_agreement'), 0, False)} | "
             f"{_n(d.get('final_score'), 0)} |")
    L.append(f"\nQuadrant: **{d.get('quadrant')}**")
    if d.get("changed"):
        L.append(f"\n**Signal change:** {d.get('change_reason')}")
    else:
        L.append(f"\nSignal unchanged ({d.get('duration_days')} session(s)).")
    L.append("\n## Forecasts (multi-horizon, probabilistic)")
    L.append("| Horizon | Expected return | P(up) | 80% interval | P(>+5%) | P(<-5%) | P(maxDD>10%) | Confidence |\n|---|---|---|---|---|---|---|---|")
    for h, f in sorted(st.get("forecasts", {}).items(), key=lambda kv: int(kv[0])):
        iv = f.get("interval", [None, None])
        L.append(f"| {h}D | {_p(f.get('expected_return'))} | {_p(f.get('p_up'), 0, False)} | {_p(iv[0])} .. {_p(iv[1])} | "
                 f"{_p(f.get('p_gt5'), 0, False)} | {_p(f.get('p_lt5'), 0, False)} | {_p(f.get('p_dd10'), 0, False)} | "
                 f"{_p(f.get('confidence'), 0, False)} |")
    if fc and st.get("price"):
        iv = fc.get("interval", [np.nan, np.nan])
        L.append(f"\n{fc.get('horizon')}D price range ({int(100 * fc.get('interval_level', 0.8))}%): "
                 f"{sym}{_n(st['price'] * (1 + (iv[0] or 0)), 2)} → {sym}{_n(st['price'] * (1 + (iv[1] or 0)), 2)}")
    L.append("\n## Model consensus (primary horizon)")
    for m, p in sorted((fc.get("model_preds") or {}).items(), key=lambda kv: -kv[1]["ret"]):
        w = (fc.get("ensemble_weights") or {}).get(m)
        L.append(f"- {m}: {_p(p['ret'], 2)} (P(up) {_p(p['p_up'], 0, False)})" + (f", weight {w:+.2f}" if w is not None else ""))
    L.append(f"- **ENSEMBLE ({fc.get('ensemble_method')})**: {_p(fc.get('expected_return'), 2)}")
    L.append("\n## Market regime & volatility")
    L.append(f"{rg.get('regime')} / {rg.get('volatility_label')} volatility (realised 20d {_p(rg.get('realized_vol_20d'), 1, False)}, "
             f"percentile {_p(rg.get('vol_percentile'), 0, False)}); HMM stress probability {_p(rg.get('hmm_stress_probability'), 0, False)}; "
             f"drawdown {_p(rg.get('drawdown'))}; {rg.get('days_in_regime')} sessions in regime.")
    L.append("\n## Signal components (why the signal exists)")
    L.append("| Component | Score | Contribution | Evidence |\n|---|---|---|---|")
    for k, c in d.get("components", {}).items():
        L.append(f"| {k} | {_n(c.get('score'), 0)} | {d.get('contributions', {}).get(k, 0):+.1f} | "
                 f"{'; '.join(c.get('evidence', [])[:2])} |")
    com = st.get("committee", {})
    for title, key in (("Bull case", "bull_case"), ("Bear case", "bear_case"), ("Neutral case", "neutral_case"),
                       ("Main risks", "key_risks")):
        L.append(f"\n## {title}")
        for x in com.get(key, [])[:8] or ["(none)"]:
            L.append(f"- {x}")
    sk = com.get("skeptic", {})
    if sk:
        L.append("\n## Skeptic (counter-case)")
        for x in (sk.get("process_risks") or [])[:8]:
            L.append(f"- {x}")
    if d.get("contradictions"):
        L.append("\n## ⚠ Contradictions")
        for x in d["contradictions"]:
            L.append(f"- {x}")
    L.append("\n## What would change the signal?")
    for x in d.get("what_would_change", []):
        L.append(f"- {x}")
    L.append("\n## Macro condition")
    for k, v in (st.get("macro_snapshot") or {}).items():
        if v is not None and k in ("curve_10y3m", "hy_oas", "cpi_yoy", "unrate", "real_yield_10y", "fed_funds", "nfci", "sahm_rt"):
            L.append(f"- {k}: {_n(v, 3)}")
    if not st.get("macro_snapshot"):
        L.append("- macro data unavailable")
    n = st.get("news", {})
    L.append("\n## News sentiment & major events")
    if n.get("available"):
        s = n.get("sentiment", {})
        L.append(f"Weighted sentiment {_n(s.get('score'), 2)} from {s.get('n')} relevant articles; labels {s.get('label_counts')}.")
        for e in sorted(n.get("events", []), key=lambda e: -e["magnitude"] * e["confidence"])[:6]:
            L.append(f"- [{e['category']}] {e.get('title', '')[:120]} — {e['direction']} (mag {e['magnitude']:.0f}, conf {e['confidence']:.0f})")
    else:
        L.append(f"News unavailable: {n.get('reason')}")
    an = st.get("analogues", {})
    if an.get("analogues"):
        L.append("\n## Historical analogues")
        L.append("| Date | Similarity | Regime | 5D | 20D | 60D | Max DD 60D |\n|---|---|---|---|---|---|---|")
        for a in an["analogues"][:8]:
            L.append(f"| {a['date']} | {_n(a['similarity'], 2)} | {a.get('regime')} | {_p(a.get('ret_5d'))} | {_p(a.get('ret_20d'))} | "
                     f"{_p(a.get('ret_60d'))} | {_p(a.get('max_dd_60d'))} |")
    L.append("\n## Stress scenarios (SCENARIOS, not predictions)")
    for s_ in st.get("stress", [])[:9]:
        L.append(f"- {s_['scenario']}: {_p(s_.get('estimated_vusa_impact'))} ({s_.get('basis')})")
    L.append("\n## Model performance (out-of-sample, primary horizon)")
    for m, v in (fc.get("ensemble_comparison") or {}).items():
        L.append(f"- {m}: DA {_p(v.get('directional_accuracy'), 1, False)}, IC {_n(v.get('ic_spearman'), 3)}, "
                 f"RMSE {_n(v.get('rmse'), 4)}, Brier {_n(v.get('brier'), 4)} (n={v.get('n')})")
    cal = fc.get("calibration", {})
    if cal:
        L.append(f"- Calibration ({cal.get('method')}): ECE raw {_n(cal.get('raw', {}).get('ece'), 3)} → "
                 f"{_n(cal.get('calibrated', {}).get('ece'), 3)}; conformal coverage {_p((fc.get('conformal') or {}).get('coverage'), 0, False)}")
    for k in ("model_drift", "feature_drift"):
        if st.get(k, {}).get("message"):
            L.append(f"- {st[k]['message']}")
    L.append("\n## Data quality")
    L.append(f"Score {_n(st.get('data_quality_score'), 0)}/100. Leakage audit: "
             f"{'PASSED' if st.get('leakage_audit', {}).get('passed') else 'FAILED / not run'}.")
    for w in st.get("warnings", [])[:10]:
        L.append(f"- {w}")
    sa = st.get("self_audit", {})
    if sa:
        L.append("\n## Self-audit")
        for k, v in sa.items():
            L.append(f"\n**{k}**")
            for x in v[:6]:
                L.append(f"- {x}")
    L.append("\n## Explanation")
    L.append(st.get("explanation", ""))
    L.append("\n---\n*Decision-support research output. Probabilistic, not a guarantee and not investment advice. "
             "No trades are placed by this application.*")
    md = "\n".join(L)
    return md, _md_to_html(md)


def _md_to_html(md: str) -> str:
    """Tiny markdown -> HTML converter (headings, tables, lists, bold) - no dependency."""
    out, in_table, in_list = [], False, False
    for line in md.splitlines():
        esc = _html.escape(line)
        esc = _bold(esc)
        if line.startswith("|"):
            cells = [c.strip() for c in line.strip("|").split("|")]
            if set("".join(cells)) <= set("-: "):
                continue
            if not in_table:
                out.append("<table>")
                in_table = True
                out.append("<tr>" + "".join(f"<th>{_bold(_html.escape(c))}</th>" for c in cells) + "</tr>")
            else:
                out.append("<tr>" + "".join(f"<td>{_bold(_html.escape(c))}</td>" for c in cells) + "</tr>")
            continue
        if in_table:
            out.append("</table>")
            in_table = False
        if line.startswith("- "):
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{esc[2:]}</li>")
            continue
        if in_list:
            out.append("</ul>")
            in_list = False
        if line.startswith("# "):
            out.append(f"<h1>{esc[2:]}</h1>")
        elif line.startswith("## "):
            out.append(f"<h2>{esc[3:]}</h2>")
        elif line.startswith("> "):
            out.append(f"<div class='warn'>{esc[5:] if esc.startswith('&gt; ') else esc}</div>")
        elif line.strip() == "---":
            out.append("<hr>")
        elif line.strip():
            out.append(f"<p>{esc}</p>")
    if in_table:
        out.append("</table>")
    if in_list:
        out.append("</ul>")
    css = ("body{font-family:Segoe UI,Arial,sans-serif;max-width:1100px;margin:24px auto;padding:0 16px;color:#1b1f24;"
           "background:#fff}table{border-collapse:collapse;margin:8px 0;width:100%}td,th{border:1px solid #d0d7de;"
           "padding:4px 8px;font-size:13px;text-align:left}th{background:#f3f5f7}h2{border-bottom:1px solid #d0d7de;"
           "padding-bottom:4px;margin-top:28px}.warn{background:#fff4ce;border:1px solid #e5c100;padding:8px;border-radius:6px}")
    return f"<!doctype html><html><head><meta charset='utf-8'><title>VUSA Daily Report</title><style>{css}</style></head><body>" \
           + "\n".join(out) + "</body></html>"


def _bold(s: str) -> str:
    parts = s.split("**")
    return "".join(f"<b>{p}</b>" if i % 2 else p for i, p in enumerate(parts))
